import React, { HTMLAttributes } from "react";
// TODO: style use type detection
import "{2}";
// Attention: This file is generated by "yarn icon", do not modify

export enum IconClass {
  // {1}
}


interface Props extends HTMLAttributes<HTMLSpanElement> {
  type: IconClass;
  text?: string;
  textPosition: "left" | "right";
}

export default class Component extends React.PureComponent<Props> {
  public static defaultProps = {
    textPosition: "right"
  };

  render() {
    const { type, text, textPosition, className, ...restProps } = this.props;
    return (
      <i
        className={`iconfont ${type} ${className ? className : ""}`}
        {...restProps}
      />
    );
  }
}
